<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServicesSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('services')->insert([
            [
                'id' => 1,
                'token' => 'RheydTPiTl',
                'type' => 'PASSPORT',
                'name' => 'ePassport Fee',
                'fund_source_id' => 5,
                'amount' => 950.00,
                'datetime_created' => '2024-09-17 06:55:06',
                'created_by' => 'superadmin2',
                'status' => 1,
            ],
            [
                'id' => 2,
                'token' => 'b9ThK8IaMf',
                'type' => 'PASSPORT',
                'name' => 'ePassport - Expedite Fee',
                'fund_source_id' => 2,
                'amount' => 250.00,
                'datetime_created' => '2024-09-17 07:06:13',
                'created_by' => 'superadmin2',
                'status' => 1,
            ],
            [
                'id' => 3,
                'token' => 'Lwc_8lNMUF',
                'type' => 'PASSPORT',
                'name' => 'ePassport - Penalty',
                'fund_source_id' => 5,
                'amount' => 350.00,
                'datetime_created' => '2024-09-17 07:38:07',
                'created_by' => 'superadmin2',
                'status' => 1,
            ],
            [
                'id' => 4,
                'token' => 'Nx3j2OtfEM',
                'type' => 'AUTHENTICATION',
                'name' => 'Apostille BTR Regular Fund',
                'fund_source_id' => 5,
                'amount' => 50.00,
                'datetime_created' => '2024-09-19 02:26:54',
                'created_by' => 'superadmin2',
                'status' => 1,
            ],
            [
                'id' => 5,
                'token' => 'dTlZrzbXjg',
                'type' => 'AUTHENTICATION',
                'name' => 'Apostille Office of the President',
                'fund_source_id' => 3,
                'amount' => 50.00,
                'datetime_created' => '2024-09-19 02:28:31',
                'created_by' => 'superadmin2',
                'status' => 1,
            ],
            [
                'id' => 6,
                'token' => 'XlcPJiojH2',
                'type' => 'AUTHENTICATION',
                'name' => 'Apostille Provident Fund',
                'fund_source_id' => 6,
                'amount' => 100.00,
                'datetime_created' => '2024-09-19 02:29:09',
                'created_by' => 'superadmin2',
                'status' => 1,
            ],
            [
                'id' => 7,
                'token' => 'NcxEXH-XJ5',
                'type' => 'AUTHENTICATION',
                'name' => 'Apostille BTR Regular Fund - Expedite',
                'fund_source_id' => 5,
                'amount' => 50.00,
                'datetime_created' => '2024-09-19 02:43:53',
                'created_by' => 'superadmin2',
                'status' => 1,
            ],
            [
                'id' => 8,
                'token' => 'pAELiAndRn',
                'type' => 'PASSPORT',
                'name' => 'Passport Extension Fee',
                'fund_source_id' => 5,
                'amount' => 200.00,
                'datetime_created' => '2024-10-17 02:41:56',
                'created_by' => 'superadmin2',
                'status' => 1,
            ],
            [
                'id' => 9,
                'token' => 'MUJpilEv0J',
                'type' => 'PASSPORT',
                'name' => 'Travel Document',
                'fund_source_id' => 5,
                'amount' => 250.00,
                'datetime_created' => '2024-10-17 02:59:21',
                'created_by' => 'superadmin2',
                'status' => 1,
            ],
            [
                'id' => 10,
                'token' => '-7goyj0W9i',
                'type' => 'OTHERS',
                'name' => 'Certification',
                'fund_source_id' => 5,
                'amount' => 100.00,
                'datetime_created' => '2024-10-17 03:00:16',
                'created_by' => 'superadmin2',
                'status' => 1,
            ],
            [
                'id' => 11,
                'token' => 'le5DiktuSQ',
                'type' => 'OTHERS',
                'name' => 'Regular Fund',
                'fund_source_id' => 5,
                'amount' => 1.00,
                'datetime_created' => '2024-12-01 13:02:23',
                'created_by' => 'superadmin2',
                'status' => 1,
            ],
            [
                'id' => 12,
                'token' => 'QfD3qqRWOr',
                'type' => 'NOTARIALS',
                'name' => 'Report of Birth/Marriage/Death',
                'fund_source_id' => 5,
                'amount' => 25.00,
                'datetime_created' => '2024-12-05 00:38:52',
                'created_by' => 'superadmin2',
                'status' => 1,
            ],
        ]);
    }
}
