services:
    nginx:
        image: nginx:1.27-alpine
        container_name: cashiering-nginx
        depends_on: [php]
        ports:
            - "8088:80"
        volumes:
            - app_code:/var/www/html:ro
            - storage_data:/var/www/html/storage
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        restart: always

    php:
        image: dfa-cashiering-client-php:latest
        container_name: cashiering-php
        depends_on: [mysql]
        volumes:
            - app_code:/var/www/html
            - storage_data:/var/www/html/storage
        environment:
            APP_ENV: production
            APP_DEBUG: false
            APP_KEY: base64:ReplaceWithYourAppKey
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: cashiering
            DB_USERNAME: cashier
            DB_PASSWORD: secret123
            SERVER_API_URL: 10.253.85.23
            APP_MODE: server
        restart: always

    mysql:
        image: mysql:8.0
        container_name: cashiering-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: cashiering
            MYSQL_USER: cashier
            MYSQL_PASSWORD: secret123
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
    storage_data:
    app_code:
