version: "3.9"

services:
    nginx:
        image: nginx:1.27-alpine
        container_name: cashiering-nginx
        depends_on: [php]
        ports:
            - "8088:80"
        volumes:
            - app_code:/var/www/html:ro
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - storage_data:/var/www/html/storage   # persistent runtime data only
        restart: always
        networks:
            - cashiering-net

    php:
        image: ${REGISTRY_HOST}/dfa-cashiering-client-php:latest
        container_name: cashiering-php
        depends_on: [mysql]
        environment:
            APP_ENV: ${APP_ENV}
            APP_DEBUG: ${APP_DEBUG}
            APP_KEY: ${APP_KEY}
            APP_MODE: ${APP_MODE}
            SERVER_API_URL: ${SERVER_API_URL}

            DB_CONNECTION: ${DB_CONNECTION}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        volumes:
            - app_code:/var/www/html
            - storage_data:/var/www/html/storage   # Only storage writes persist
        restart: always
        networks:
            - cashiering-net

    mysql:
        image: mysql:8.0
        container_name: cashiering-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - cashiering-net

    queue:
        image: ${REGISTRY_HOST}/dfa-cashiering-client-php:latest
        container_name: cashiering-queue
        depends_on:
            - php
            - mysql
        command: php artisan queue:work --verbose --timeout=120 --tries=3
        env_file:
            - .env.docker
        volumes:
            - app_code:/var/www/html
            - storage_data:/var/www/html/storage
        restart: always
        networks:
            - cashiering-net

networks:
    cashiering-net:

volumes:
    mysql_data:
    storage_data:
    app_code:
